
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: movie_recommender
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"

    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./back
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - ./back:/app

volumes:
  db_data:
