services:
  - type: web
    name: movie-api-backend
    env: node
    rootDir: back
    buildCommand: npm install && npm run build
    startCommand: |
      ls -la dist && \
      (node dist/main.js || \
      node ./dist/main.js || \
      node back/dist/main.js || \
      node src/dist/main.js || \
      npx nest start:prod || \
      npm run start:prod || \
      echo "❌ Ningún método de arranque funcionó. Render se pasó de fresco." && exit 1)
    envVars:
      - key: NODE_ENV
        value: production
      - key: AUTH0_AUDIENCE
        sync: false
      - key: AUTH0_CALLBACK_URL
        sync: false
      - key: AUTH0_CLIENT_ID
        sync: false
      - key: AUTH0_CLIENT_SECRET
        sync: false
      - key: AUTH0_DOMAIN
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: GOOGLE_CALLBACK_URL
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: JWT_SECRET
        sync: false
