services:
  - type: web
    name: movie-api-backend
    env: node
    region: oregon
    rootDir: back
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: AUTH0_AUDIENCE
        sync: false
      - key: AUTH0_CALLBACK_URL
        sync: false
      - key: AUTH0_CLIENT_ID
        sync: false
      - key: AUTH0_CLIENT_SECRET
        sync: false
      - key: AUTH0_DOMAIN
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: GOOGLE_CALLBACK_URL
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: JWT_SECRET
        sync: false
