services:
  - type: web
    name: movie-api-backend
    rootDir: back
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      # Si necesitas más variables, agrégalas aquí
